# Ansible varibales can declared in many ways
# can be accessed with {{  }}

- name: play level varibales
  hosts: localhost
  connection: local
  vars: 
   url: playlevel.example.com
  tasks:
    - name: print url
      ansible.builtin.debug:
       msg: url - {{ url }} 

# ansible-playbook 02.variables.yaml


- name: task level varibales
  hosts: localhost
  connection: local
  tasks:
    - name: print url
      ansible.builtin.debug:
       msg: url - {{ url }} 
      vars: 
       url: tasklevel.example.com



# command line can be declared at run like : ansible-playbook 02.variables.yaml -e url=cli_level.exmaple.com
# variable precedence 
# 1)cli level.
# 2)task level
# 3)play level
# variable types

- name: types of varibales
  hosts: localhost
  connection: local
  vars: 
    x: abc
    b: 100
    c: true
  tasks:
    - name: print url
      ansible.builtin.debug:
       msg: x - {{ x }} ,y - {{ y }} ,z - {{ z }} 